# Site settings
title: 情书
email: mincong.he@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mincong.net" # the base hostname & protocol for your site
twitter_username: hemincong
github_username:  hemincong

# Build settings
markdown: kramdown
